2019-06-24 17:59:40,809 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-06-28 19:10:24,590 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-06-28 19:12:45,123 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-06-28 22:07:48,018 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-06-29 09:01:53,846 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-06-29 09:02:28,980 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-06-30 16:34:57,616 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-06-30 16:35:57,473 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-07-10 16:40:20,726 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-07-10 20:49:55,201 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-07-10 21:26:39,861 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-07-11 03:06:39,353 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-07-11 03:06:54,845 ERROR Exception on / [GET] [in c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py:(lineno)d]
Traceback (most recent call last):
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\user\Documents\microblog\app\routes.py", line 22, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\user\Documents\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\user\Documents\microblog\app\templates\base.html", line 36, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\user\Documents\microblog\app\templates\index.html", line 21, in block "content"
    {% for post in posts %}
TypeError: 'method' object is not iterable
2019-07-11 03:10:42,444 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-07-11 03:10:45,663 ERROR Exception on / [GET] [in c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py:(lineno)d]
Traceback (most recent call last):
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\user\Documents\microblog\app\routes.py", line 22, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\user\Documents\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\user\Documents\microblog\app\templates\base.html", line 36, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\user\Documents\microblog\app\templates\index.html", line 21, in block "content"
    {% for post in posts %}
TypeError: 'method' object is not iterable
2019-07-11 03:15:33,558 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-07-11 03:15:41,616 ERROR Exception on / [GET] [in c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py:(lineno)d]
Traceback (most recent call last):
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\user\Documents\microblog\app\routes.py", line 22, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\user\Documents\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\user\Documents\microblog\app\templates\base.html", line 36, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\user\Documents\microblog\app\templates\index.html", line 21, in block "content"
    {% for post in posts %}
TypeError: 'method' object is not iterable
2019-07-11 03:18:32,398 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-07-22 12:30:27,580 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
2019-07-22 13:01:57,786 INFO Microblog startup [in C:\Users\user\Documents\microblog\app\__init__.py:(lineno)d]
