2019-08-13 14:36:02,703 ERROR: Exception on /explore [GET] [in c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\DELL\Desktop\microblog\app\routes.py", line 239, in explore
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-08-20 06:07:39,786 INFO: Microblog startup [in C:\Users\DELL\Desktop\microblog\app\__init__.py:47]
2019-08-20 06:08:43,160 ERROR: Exception on /index [GET] [in c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\DELL\Desktop\microblog\app\routes.py", line 37, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-10-15 13:58:42,671 INFO: Microblog startup [in C:\Users\DELL\Desktop\microblog\app\__init__.py:47]
2019-10-15 14:00:40,995 ERROR: Exception on /index [GET] [in c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\DELL\Desktop\microblog\app\routes.py", line 37, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-10-15 14:00:49,111 ERROR: Exception on /index [GET] [in c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\DELL\Desktop\microblog\app\routes.py", line 37, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-10-15 14:00:50,604 ERROR: Exception on /index [GET] [in c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\DELL\Desktop\microblog\app\routes.py", line 37, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-10-15 14:00:55,925 ERROR: Exception on /user/hope [GET] [in c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\DELL\Desktop\microblog\app\routes.py", line 118, in user
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-10-15 14:00:59,890 ERROR: Exception on /user/hope [GET] [in c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dell\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\DELL\Desktop\microblog\app\routes.py", line 118, in user
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
